<a href="https://colab.research.google.com/github/Patrick-EsLo/Easy2Pay/blob/master/Task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Atividade 1 - Grupo2 31/08/2021 IA 10E
Patrick Lopes Tia 31613845 
Mateus Rodrigues Tia 41634276
Gabriel Panema Tia 41780337
Vitor Cabral Tia 31701620
Ricardo Daracdjian Tia 31728758

Exer 1 e 2-)



In [ ]:
x = 4
y = 2.5
texto = "cadeia de texto"
lista1 = [ x, y, texto]
print(lista1)

[4, 2.5, 'cadeia de texto']


Exe 3-)

In [ ]:
import numpy as np
a = np.linspace(0,1000,100)
print(a)

[   0.           10.1010101    20.2020202    30.3030303    40.4040404
   50.50505051   60.60606061   70.70707071   80.80808081   90.90909091
  101.01010101  111.11111111  121.21212121  131.31313131  141.41414141
  151.51515152  161.61616162  171.71717172  181.81818182  191.91919192
  202.02020202  212.12121212  222.22222222  232.32323232  242.42424242
  252.52525253  262.62626263  272.72727273  282.82828283  292.92929293
  303.03030303  313.13131313  323.23232323  333.33333333  343.43434343
  353.53535354  363.63636364  373.73737374  383.83838384  393.93939394
  404.04040404  414.14141414  424.24242424  434.34343434  444.44444444
  454.54545455  464.64646465  474.74747475  484.84848485  494.94949495
  505.05050505  515.15151515  525.25252525  535.35353535  545.45454545
  555.55555556  565.65656566  575.75757576  585.85858586  595.95959596
  606.06060606  616.16161616  626.26262626  636.36363636  646.46464646
  656.56565657  666.66666667  676.76767677  686.86868687  696.96969697
  707.0

Exer 4-)

In [ ]:
mat = a.reshape(10,10)
print(mat)

[[   0.           10.1010101    20.2020202    30.3030303    40.4040404
    50.50505051   60.60606061   70.70707071   80.80808081   90.90909091]
 [ 101.01010101  111.11111111  121.21212121  131.31313131  141.41414141
   151.51515152  161.61616162  171.71717172  181.81818182  191.91919192]
 [ 202.02020202  212.12121212  222.22222222  232.32323232  242.42424242
   252.52525253  262.62626263  272.72727273  282.82828283  292.92929293]
 [ 303.03030303  313.13131313  323.23232323  333.33333333  343.43434343
   353.53535354  363.63636364  373.73737374  383.83838384  393.93939394]
 [ 404.04040404  414.14141414  424.24242424  434.34343434  444.44444444
   454.54545455  464.64646465  474.74747475  484.84848485  494.94949495]
 [ 505.05050505  515.15151515  525.25252525  535.35353535  545.45454545
   555.55555556  565.65656566  575.75757576  585.85858586  595.95959596]
 [ 606.06060606  616.16161616  626.26262626  636.36363636  646.46464646
   656.56565657  666.66666667  676.76767677  686.86868687  

Exer 5-)

In [ ]:
print(mat[3:8,4:9])

[[343.43434343 353.53535354 363.63636364 373.73737374 383.83838384]
 [444.44444444 454.54545455 464.64646465 474.74747475 484.84848485]
 [545.45454545 555.55555556 565.65656566 575.75757576 585.85858586]
 [646.46464646 656.56565657 666.66666667 676.76767677 686.86868687]
 [747.47474747 757.57575758 767.67676768 777.77777778 787.87878788]]


Exer 6-)

In [ ]:
lista3 = []
for x in range(1,26,2):
  lista3.append(x)
print(lista3)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25]


Exer 7-)

In [ ]:
i = 1
lista3 = []
while i < 26:
  lista3.append(i)
  i += 2
print(lista3)
  

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25]


Exer 8-)

In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame(mat)
print(df)

            0           1           2  ...           7           8            9
0    0.000000   10.101010   20.202020  ...   70.707071   80.808081    90.909091
1  101.010101  111.111111  121.212121  ...  171.717172  181.818182   191.919192
2  202.020202  212.121212  222.222222  ...  272.727273  282.828283   292.929293
3  303.030303  313.131313  323.232323  ...  373.737374  383.838384   393.939394
4  404.040404  414.141414  424.242424  ...  474.747475  484.848485   494.949495
5  505.050505  515.151515  525.252525  ...  575.757576  585.858586   595.959596
6  606.060606  616.161616  626.262626  ...  676.767677  686.868687   696.969697
7  707.070707  717.171717  727.272727  ...  777.777778  787.878788   797.979798
8  808.080808  818.181818  828.282828  ...  878.787879  888.888889   898.989899
9  909.090909  919.191919  929.292929  ...  979.797980  989.898990  1000.000000

[10 rows x 10 columns]


Exer 9-)

In [ ]:
df[[4,5,6,7,8]].iloc[3:8]

4           5           6           7           8
3  343.434343  353.535354  363.636364  373.737374  383.838384
4  444.444444  454.545455  464.646465  474.747475  484.848485
5  545.454545  555.555556  565.656566  575.757576  585.858586
6  646.464646  656.565657  666.666667  676.767677  686.868687
7  747.474747  757.575758  767.676768  777.777778  787.878788

Exer 10-)

In [ ]:
# Titanic
url = "https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv"
titanic = pd.read_csv(url)
titanic.iloc[0:10]

Survived  Pclass  ... Parents/Children Aboard     Fare
0         0       3  ...                       0   7.2500
1         1       1  ...                       0  71.2833
2         1       3  ...                       0   7.9250
3         1       1  ...                       0  53.1000
4         0       3  ...                       0   8.0500
5         0       3  ...                       0   8.4583
6         0       1  ...                       0  51.8625
7         0       3  ...                       1  21.0750
8         1       3  ...                       2  11.1333
9         1       2  ...                       0  30.0708

[10 rows x 8 columns]